# Generated by Django 5.0.6 on 2026-07-29 10:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Trainer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True)),
                ('Where_did_Hear_us', models.CharField(blank=True, choices=[('Social Media', 'Social Media'), ('Website', 'Website'), ('Friend', 'Friend'), ('Advertisement', 'Advertisement'), ('Other', 'Other')], max_length=100)),
                ('college', models.CharField(blank=True, max_length=100)),
                ('Degree', models.CharField(blank=True, choices=[('High School', 'High School'), ('Diploma A1', 'Diploma A1'), ('Bachelors', 'Bachelors'), ('Masters', 'Masters'), ('PhD', 'PhD')], max_length=100)),
                ('upload_cv', models.FileField(blank=True, null=True, upload_to='trainer_cvs/')),
                ('Recommendation_letter', models.FileField(blank=True, null=True, upload_to='trainer_recommendations/')),
                ('level', models.CharField(choices=[('Beginner', 'Beginner'), ('Intermediate', 'Intermediate'), ('Advanced', 'Advanced')], default='Beginner', max_length=20)),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='trainer_profiles/')),
                ('Country', models.CharField(blank=True, max_length=100)),
                ('City', models.CharField(blank=True, max_length=100)),
                ('Adress', models.CharField(blank=True, max_length=255)),
                ('Phone_number', models.CharField(max_length=15)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
