# Generated by Django 5.0.6 on 2026-07-29 15:02

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TrainerData', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainer',
            name='Experience_year',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='trainer',
            name='Status',
            field=models.CharField(choices=[('New', 'New'), ('Under Review', 'Under Review'), ('Communicated', 'Communicated'), ('Contract Signed', 'Contract Signed'), ('Training Session Conducted', 'Training Session Conducted'), ('Active to Our Course', 'Active to Our Course'), ('Rejected to Our Course', 'Rejected to Our Course'), ('Other', 'Other')], default='New', max_length=50),
        ),
        migrations.AddField(
            model_name='trainer',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
