# Generated by Django 5.0.6 on 2026-07-31 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TrainerData', '0002_trainer_experience_year_trainer_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainer',
            name='attended_cybersecurity_course_before',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=10),
        ),
        migrations.AddField(
            model_name='trainer',
            name='cybersecurity_course_applied',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
