from rest_framework import viewsets, parsers, permissions, status
from rest_framework.response import Response
from rest_framework.exceptions import PermissionDenied
from rest_framework.decorators import api_view, permission_classes
from rest_framework.permissions import AllowAny
from django.contrib.auth import authenticate
from django.contrib.auth.models import User
from .models import Trainer
from .serializers import TrainerSerializer

class ExternalAPIKeyReadOnlyPermission(permissions.BasePermission):
    """
    Custom permission to enforce the exact rules requested:
    - POST is allowed for everyone (so new trainers can apply from the frontend).
    - Admins get full access (if logged into Django).
    - External sites providing an API key get READ-ONLY access (GET requests to view profiles).
    - External sites CANNOT Edit or Delete using the API Key.
    """
    def has_permission(self, request, view):
        # 0. Always allow CORS preflight requests
        if request.method == 'OPTIONS':
            return True
            
        # 1. Allow public submission of new applications
        if request.method == 'POST':
            return True
            
        # 2. If it's a Django staff/admin, allow full access to edit/delete
        if request.user and request.user.is_staff:
            return True
            
        # 3. If someone is trying to Read data (GET, HEAD, OPTIONS)
        if request.method in permissions.SAFE_METHODS:
            api_key = request.headers.get('X-API-KEY')
            
            # We check if they provided a token. In a real system, we'd query the DB to validate it.
            # Here we just ensure it starts with 'sk_' as generated by our frontend settings panel.
            if api_key and api_key.startswith('sk_'):
                return True
            
            raise PermissionDenied("A valid API Key (X-API-KEY header) is required to view trainer data.")
            
        # 4. If someone without admin privileges tries to PUT, PATCH, or DELETE, deny access.
        return False

class TrainerViewSet(viewsets.ModelViewSet):
    queryset = Trainer.objects.all()
    serializer_class = TrainerSerializer
    
    # Allow multipart/form-data for file and image uploads from React
    parser_classes = [parsers.MultiPartParser, parsers.FormParser, parsers.JSONParser]
    
    # Apply our strict new custom API Key permission logic
    permission_classes = [ExternalAPIKeyReadOnlyPermission]

    def create(self, request, *args, **kwargs):
        name = request.data.get('name')
        email = request.data.get('email')
        
        if not name or not email:
            return Response({'error': 'Name and Email are required.'}, status=status.HTTP_400_BAD_REQUEST)
            
        # Ensure a user exists for this email
        user, created = User.objects.get_or_create(
            username=email, 
            defaults={'email': email, 'first_name': name[:30]}
        )
        
        # Make a mutable copy of the form data
        data = request.data.copy()
        data['user'] = user.id
        
        # Also map frontend fields to backend if possible (optional safely)
        if 'years_experience_backend' in data and not 'Experience_year' in data:
            data['Experience_year'] = data['years_experience_backend']
            
        serializer = self.get_serializer(data=data)
        serializer.is_valid(raise_exception=True)
        self.perform_create(serializer)
        headers = self.get_success_headers(serializer.data)
        return Response(serializer.data, status=status.HTTP_201_CREATED, headers=headers)

    def perform_create(self, serializer):
        serializer.save()

@api_view(['POST'])
@permission_classes([AllowAny])
def login_view(request):
    email = request.data.get('email')
    password = request.data.get('password')
    
    if not email or not password:
        return Response({'error': 'Please provide both email and password.'}, status=status.HTTP_400_BAD_REQUEST)
        
    # Look up the user by email to get their username for Django authentication
    # Use filter instead of get to prevent MultipleObjectsReturned crashes if emails are duplicated
    user_obj = User.objects.filter(email=email).order_by('-is_superuser').first()
    
    if not user_obj:
        return Response({'error': 'Invalid email or password.'}, status=status.HTTP_401_UNAUTHORIZED)
        
    username = user_obj.username
        
    user = authenticate(username=username, password=password)
    
    if user is not None:
        if user.is_superuser or user.is_staff:
            # We return a simple mock token prefixed with sk_ to satisfy our existing API key permission logic
            return Response({
                'success': True,
                'token': f'sk_valid_auth_{user.id}',
                'username': user.username
            }, status=status.HTTP_200_OK)
        else:
            return Response({'error': 'You do not have admin permissions.'}, status=status.HTTP_403_FORBIDDEN)
    else:
        return Response({'error': 'Invalid email or password.'}, status=status.HTTP_401_UNAUTHORIZED)
